# Use the official Node.js image as the base image for frontend
FROM node:20.0.0-alpine AS backend

# Set the working directory for frontend
WORKDIR /app/quirknotes/backend

# Copy frontend package files
COPY quirknotes/backend/package*.json ./

# Install frontend dependencies
RUN npm install

# Copy backend source code
COPY quirknotes/backend ./

# Command to run server backend
CMD ["npm", "start"]